# Generated by Django 3.2.24 on 2024-03-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boxes',
            new_name='Box',
        ),
    ]
