# Generated by Django 3.2.24 on 2024-03-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_rename_boxes_box'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Box',
            new_name='Product',
        ),
    ]
