# Generated by Django 3.2.24 on 2024-05-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_birth',
        ),
    ]
